@HotelListing.API_HostAddress = http://localhost:5240

###

GET {{HotelListing.API_HostAddress}}/api/hotels

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "id": 4,
  "name": "Grandplaaza",
  "address": "123 Main St",
  "rating": 4.5
}

###

@id=1
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  //Hotel
}

###
